<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DrillSchemaEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrillSchemaEventRepository extends EntityRepository
{
}
