<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseRepository extends EntityRepository
{
    /**
     * @param $licenseId
     * @param $addonKey
     *
     * @return License
     */
    public function findOrCreate($licenseId, $addonKey)
    {
        $license = $this->findOneBy([
            'licenseId' => $licenseId,
            'addonKey' => $addonKey
        ]);

        if (!$license) {
            $license = new License();
        }

        return $license;
    }

    public function findFiltered($filters)
    {
        $criteria = [];

        if (!empty($filters['addonKey'])) {
            $criteria['addonKey'] = $filters['addonKey'];
        }

        if (!empty($filters['licenseType'])) {
            $criteria['licenseType'] = $filters['licenseType'];
        }

        $order[$filters['sort_field']] = $filters['sort_direction'];
        $limit = $filters['limit'];

        return $this->findBy($criteria, $order, $limit);
    }

    public function getAddonChoices()
    {
        $result = $this->createQueryBuilder('l')
            ->select(['l.addonKey', 'l.addonName'])
            ->distinct()
            ->getQuery()
            ->getResult();

        $choices = [];
        foreach ($result as $choice) {
            $choices[$choice['addonKey']] = $choice['addonName'];
        }

        return $choices;
    }
}
